@ Generated by gcc 2.95.3 20010315 (release) for Thumb/coff
	.code	16
.gcc2_compiled.:
.text
	.align	2
	.globl	sub_800058C
	.thumb_func
sub_800058C:
	ldr	r0, .L3
	ldrh	r0, [r0]
	bx	lr
.L4:
	.align	2
.L3:
	.word	33685504
