#!/usr/bin/env python3
import yaml
import sys
import os

def main():
    if len(sys.argv) < 2:
        print("Usage: disasm.py <config.yaml>")
        sys.exit(1)
        
    config_path = sys.argv[1]
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)
        
    rom_path = config.get("rom", "baserom.gba")
    out_dir = config.get("out_dir", "asm")
    
    os.makedirs(out_dir, exist_ok=True)
    
    banks = config.get("banks", [])
    
    for bank in banks:
        name = bank["name"]
        start = bank["start"]
        end = bank["end"]
        sections = bank.get("sections", [])
        
        out_path = os.path.join(out_dir, f"{name}.s")
        with open(out_path, 'w') as out_f:
            out_f.write(f"@ {name}.s — Generated by disasm.py\n")
            out_f.write(f"@ ROM range: 0x{start:06X} - 0x{end:06X}\n\n")
            
            # Default to Thumb text if not otherwise specified at top
            out_f.write("    .text\n")
            out_f.write("    .thumb\n\n")
            
            current_offset = start
            
            for section in sections:
                sec_type = section.get("type", "incbin")
                sec_start = section["start"]
                sec_end = section["end"]
                sec_label = section.get("label", None)
                sec_mode = section.get("mode", None)
                
                # Sanity check ranges
                if sec_start < current_offset:
                    print(f"Error in {name}: Section starting at 0x{sec_start:06X} overlaps previous section.")
                    sys.exit(1)
                
                # Fill gaps with incbin
                if sec_start > current_offset:
                    gap_size = sec_start - current_offset
                    out_f.write(f"    @ Unmapped gap\n")
                    out_f.write(f"    .incbin \"{rom_path}\", 0x{current_offset:X}, 0x{gap_size:X}\n\n")
                
                if sec_label:
                    if sec_type == "code" and sec_mode == "thumb":
                        out_f.write(f"    .thumb_func\n")
                    out_f.write(f"{sec_label}:\n")
                
                if sec_type == "incbin":
                    size = sec_end - sec_start
                    out_f.write(f"    .incbin \"{rom_path}\", 0x{sec_start:X}, 0x{size:X}\n")
                else:
                    # In the future, 'code' or 'data' can invoke objdump here or dump bytes.
                    # For now, default everything not implemented to incbin.
                    size = sec_end - sec_start
                    out_f.write(f"    .incbin \"{rom_path}\", 0x{sec_start:X}, 0x{size:X}\n")
                    
                out_f.write("\n")
                current_offset = sec_end
                
            # Fill any remaining space to the end of the bank
            if current_offset < end:
                gap_size = end - current_offset
                out_f.write(f"    @ Remainder of bank\n")
                out_f.write(f"    .incbin \"{rom_path}\", 0x{current_offset:X}, 0x{gap_size:X}\n\n")

if __name__ == "__main__":
    main()
