@ Generated by gcc 2.95.3 20010315 (release) for Thumb/coff
	.code	16
.gcc2_compiled.:
	
    .align 2, 0
    .thumb_func
    .global bank_05_start
bank_05_start:
    .incbin "baserom.gba", 0x500000, 0x100000

