@ Generated by gcc 2.95.3 20010315 (release) for Thumb/coff
	.code	16
.gcc2_compiled.:
	
    .align 2, 0
    .thumb_func
    .global bank_0E_start
bank_0E_start:
    .incbin "baserom.gba", 0xE00000, 0x100000

