@ Generated by gcc 2.95.3 20010315 (release) for Thumb/coff
	.code	16
.gcc2_compiled.:
	
    .align 2, 0
    .thumb_func
    .global bank_03_start
bank_03_start:
    .incbin "baserom.gba", 0x300000, 0x100000

