@ Generated by gcc 2.95.3 20010315 (release) for Thumb/coff
	.code	16
.gcc2_compiled.:
	
    .align 2, 0
    .thumb_func
    .global sub_800B178
sub_800B178:
    .incbin "baserom.gba", 0xB178, 0xF4E88

