@ Generated by gcc 2.95.3 20010315 (release) for Thumb/coff
	.code	16
.gcc2_compiled.:
	
    .align 2, 0
    .thumb_func
    .global bank_01_start
bank_01_start:
    .incbin "baserom.gba", 0x100000, 0x100000

