@ Generated by gcc 2.95.3 20010315 (release) for Thumb/coff
	.code	16
.gcc2_compiled.:
	
    .align 2, 0
    .thumb_func
    .global bank_0C_start
bank_0C_start:
    .incbin "baserom.gba", 0xC00000, 0x100000

